sudo: false
dist: trusty

before_install:
  - wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$VERACODE_WRAPPER_VERSION/vosp-api-wrappers-java-$VERACODE_WRAPPER_VERSION.jar
  
script:
  - zip -r veracode.zip /
  - java -jar vosp-api-wrappers-java-$VERACODE_WRAPPER_VERSION.jar -vid $TEAM_ANALYSISCENTER_ID
    -vkey $TEAM_ANALYSISCENTER_KEY -action uploadandscan -appname $VERACODE_PROJECT_NAME -createprofile false
    -autoscan true -filepath veracode.zip -version "$TRAVIS_JOB_NUMBER"
