---
resources:
- name: veracode-flask-example
  type: git
  source:
    uri: https://github.com/ctcampbell/veracode-flask-example.git
    branch: master
    
- name: veracode-image
  type: docker-image
  source:
    repository: ctcampbelldocker/veracode-ci-examples

jobs:
- name: scan-with-veracode
  plan:
  - get: veracode-flask-example
  - get: veracode-image
  - task: package
    image: veracode-image
    config:
      platform: linux
      inputs:
      - name: veracode-flask-example
      outputs:
      - name: project-zip
      run:
        path: git
        args: ["--git-dir=veracode-flask-example/.git", "archive", "-o", "project-zip/veracode.zip", "HEAD"]
  - task: veracode-policy-scan
    image: veracode-image
    config:
      platform: linux
      inputs:
      - name: project-zip  
      run:
        path: /veracode/veracode-ci-examples/uploadandscan.sh
        args: [((TEAM_ANALYSISCENTER_ID)), ((TEAM_ANALYSISCENTER_KEY)), ((PROJECT_NAME)), "project-zip/veracode.zip"]
      params:
        TEAM_ANALYSISCENTER_ID:
        TEAM_ANALYSISCENTER_KEY:
        PROJECT_NAME:
